- name: tas
  value: sim/cockpit2/gauges/indicators/true_airspeed_kts_pilot
- name: vs
  value: sim/flightmodel/position/vh_ind_fpm
- name: gear_force
  value: sim/flightmodel/forces/fnrml_gear
- name: g_force
  value: sim/flightmodel2/misc/gforce_normal
- name: agl
  value: sim/flightmodel/position/y_agl
- name: elevation
  value: sim/flightmodel/position/elevation
- name: gs
  value: sim/flightmodel/position/groundspeed
- name: n1
  value: sim/cockpit2/engine/indicators/N1_percent[0]
- name: pitch
  value: sim/flightmodel/position/theta
- name: ias
  value: sim/cockpit2/gauges/indicators/airspeed_kts_pilot
- name: lat
  value: sim/flightmodel/position/latitude
- name: lng
  value: sim/flightmodel/position/longitude
- name: ts
  value: sim/network/misc/network_time_sec
- name: icao
  value: sim/aircraft/view/acf_ICAO
- name: fuel_weight
  value: sim/flightmodel/weight/m_fuel_total
- name: total_weight
  value: sim/flightmodel/weight/m_total
- name: empty_weight
  value: sim/aircraft/weight/acf_m_empty
- name: heading
  value: sim/flightmodel/position/mag_psi
- name: paused
  value: sim/time/paused
- name: sim_time
  value: sim/time/total_running_time_sec
- name: replay_mode
  value: sim/operation/prefs/replay_mode
- name: num_of_engine
  value: sim/aircraft/engine/acf_num_engines
- name: max_weight
  value: sim/aircraft/weight/acf_m_max
- name: total_flight_time
  value: sim/time/total_flight_time_sec
- name: heading_deg
  value: sim/cockpit2/gauges/indicators/heading_vacuum_deg_mag_pilot
- name: height_ft
  value: sim/cockpit2/gauges/indicators/radio_altimeter_height_ft_pilot
- name: altitude_ft
  value: sim/flightmodel/misc/h_ind
- name: mach
  value: sim/flightmodel/misc/machno
- name: bank_deg
  value: sim/flightmodel/position/true_phi
- name: alpha
  value: sim/flightmodel/position/alpha
- name: load_factor_g
  value: sim/flightmodel/misc/g_total
- name: true_track
  value: sim/flightmodel/position/hpath
- name: mag_var
  value: sim/flightmodel/position/magnetic_variation
- name: wind_deg
  value: sim/cockpit2/gauges/indicators/wind_heading_deg_mag
- name: wind_kt
  value: sim/cockpit2/gauges/indicators/wind_speed_kts
- name: oat
  value: sim/cockpit2/temperature/outside_air_temp_degc
- name: eng_running
  value: sim/flightmodel/engine/ENGN_thro
- name: eng_power
  value: sim/cockpit2/engine/indicators/power_watts
- name: brake_left
  value: sim/cockpit2/controls/left_brake_ratio
- name: brake_right
  value: sim/cockpit2/controls/right_brake_ratio
- name: brake_parking
  value: sim/cockpit2/controls/parking_brake_ratio
- name: gear_lever_down
  value: sim/cockpit2/controls/gear_handle_down
- name: pitch_control
  value: sim/cockpit2/controls/yoke_pitch_ratio
- name: roll_control
  value: sim/cockpit2/controls/yoke_roll_ratio
- name: yaw_control
  value: sim/cockpit2/controls/yoke_heading_ratio
- name: flap_lever
  value: sim/cockpit2/controls/flap_ratio
- name: speedbrake_lever
  value: sim/cockpit2/controls/speedbrake_ratio
- name: autopilot
  value: sim/cockpit/autopilot/autopilot_mode
- name: cabin_alt_ft
  value: sim/cockpit2/pressurization/indicators/cabin_altitude_ft
- name: cambin_vs_ft
  value: sim/cockpit2/pressurization/indicators/cabin_vvi_fpm
- name: nav1_course_deg
  value: sim/cockpit/radios/nav1_course_degm
- name: nav1_slope_deg
  value: sim/cockpit/radios/nav1_slope_degt
- name: nav1_dme
  value: sim/cockpit/radios/nav1_dme_dist_m
- name: loc_dev_dots
  value: sim/cockpit/radios/nav1_hdef_dot
- name: glider_dev_dots
  value: sim/cockpit/radios/nav1_vdef_dot
